Tra_dirigido/Tra_dirigido/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.historial_precio.urls')),
    path('', include('applications.productos.urls')),
    path('', include('applications.productos_seleccionados.urls')),
    #path('', include('applications.usuarios.urls')),
    re_path('', include('applications.users.urls')),
]

Tra_dirigido/applications/historial_precio/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "historial_app"

urlpatterns = [
    path('history/',
         views.ListaHistorialPrecio.as_view(),
        name="historial"),
    path('historial/<id>',
         views.ListaHistorial.as_view(),
        name="historia"),
]

Tra_dirigido/applications/productos/urls.py
from django.urls import path
from . import views


app_name = "productos_app"
urlpatterns = [
    path('ProductsPrice/',
         views.getProductoByPrice.as_view(),
         name="producto"
         ),
    path('ProductsSave/',
         views.SaveProducts.as_view(),
         name="producto-save"
         ),
    path('DelData/',
         views.BorrarDatos.as_view(),
         name="Delete"),
]

Tra_dirigido/applications/productos_seleccionados/urls.py
from django.urls import path
from . import views

app_name = "productosSeleccionado_app"

urlpatterns = [
    path('productsSelect/<pk>',
         views.IndexView.as_view(),
         name='producto-seleccionados'),
    path('Favoritos/',
         views.ConsultarFavoritos.as_view(),
         name='favoritos'),
    path('deleteFavorite/<pk>',
         views.EliminarFavorito.as_view(),
         name='delete-favorito'),
]

Tra_dirigido/applications/users/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path('',
         views.HomeIndex.as_view(),
         name='inicio'),
    path('register/',
         views.UserRegisterView.as_view(),
         name='user-register'),
    path('index/',
         views.HomeUserView.as_view(),
         name='index'),
    path('loginUser/',
         views.LoginUser.as_view(),
         name='user-login'),
    path('logOut/',
         views.LogoutView.as_view(),
         name='user-logOut'),
    path('update/',
         views.UpdatePasswordView.as_view(),
         name='user-update'),
]

Tra_dirigido/templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Compras Rentables</li>
      <li><a href="{% url 'productosSeleccionado_app:favoritos' %}">Favoritos</a></li>
      <li><a href="{% url 'productos_app:producto' %}">Productos</a></li>
      <li><a href="{% url 'historial_app:historial' %}">Historico</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
        <button type="button" class="button" onclick="window.location.href='{% url 'users_app:index' %}'">
          Usuario
        </button>
      </li>
    </ul>
  </div>
</div>

Tra_dirigido/templates/includes/headerInicio.html
<div class="top-bar">
    <div class="top-bar-right">
        <ul class="dropdown menu" data-dropdown-menu>
            <li>
                <button type="button" class="button" onclick="window.location.href='{% url 'users_app:user-login' %}'">
                    Ingresar
                </button>
            </li>
            <li class="separator" style="margin-right: 10px"></li>
            <li>
                <button type="button" class="hollow button success" onclick="window.location.href='{% url 'users_app:user-register' %}'">
                    Registrar
                </button>
            </li>
        </ul>
    </div>
</div>