Tra_dirigido/Tra_dirigido/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.historial_precio.urls')),
    path('', include('applications.productos.urls')),
    path('', include('applications.productos_seleccionados.urls')),
    #path('', include('applications.usuarios.urls')),
    re_path('', include('applications.users.urls')),
]

Tra_dirigido/applications/users/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path('',
         views.HomeIndex.as_view(),
         name='inicio'),
    path('register/',
         views.UserRegisterView.as_view(),
         name='user-register'),
    path('index/',
         views.HomeUserView.as_view(),
         name='index'),
    path('loginUser/',
         views.LoginUser.as_view(),
         name='user-login'),
    path('logOut/',
         views.LogoutView.as_view(),
         name='user-logOut'),
    path('update/',
         views.UpdatePasswordView.as_view(),
         name='user-update'),
]

Tra_dirigido/templates/usuarios/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home Usuario
{% endblock title %}

{% block content%}
    {% include 'includes/header.html'%}
    <div class="grid-container" style="height: 100vh;">
        <div class="grid-x align-center-middle" style="height: 100%;">
            <div class="cell large-8 text-center">
                <h1>Panel Usuario</h1>
            </div>
            <div class="cell large-8">
                <h3>Bienvenido: {{user.nombres}}</h3>
                <ul>
                    <li><a href="{% url 'users_app:user-logOut' %}">Cerrar Sesion</a></li>
                    <li><a href="{% url 'users_app:user-update' %}">Acualizar Datos</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content%}

Tra_dirigido/templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Acceder al Sistema
{% endblock title %}

{% block content%}
    <div class="grid-container" style="height: 100vh;">
        <div class="grid-x align-center-middle" style="height: 100%;">
            <div class="cell large-8 text-center">
                <h1>Acceder al sistema</h1>
            </div>
            <div class="cell large-4 text-center">
                <form method="POST">{% csrf_token %}
                    <div>
                        {{ form.as_p }}
                        <button type="submit" class="button expanded">Acceder</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content%}

Tra_dirigido/templates/usuarios/productsUser.html
<!-- templates/tuapp/lista_productos.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Productos del usuario</title>
</head>
<body>
    <h1>Lista de Productos</h1>

    <ul>
        {% for producto in productos %}
            <li>{{ producto.nombre }} - {{ producto.precio }}</li>
        {% endfor %}
    </ul>
</body>
</html>

Tra_dirigido/templates/usuarios/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Nuevo Usuario
{% endblock title %}

{% block content%}
    <div class="grid-container" style="height: 100vh;">
        <div class="grid-x align-center-middle" style="height: 100%;">
                <div class="cell large-4">
                    <h1>Registrar Nuevo Usuario</h1>
                </div>
                <div class="cell large-4 text-center">
                    <form method="POST">
                    {% csrf_token %}
                    <div>
                        {{ form.as_p }}
                        <button type="submit" class="button expanded">Registrar</button>
                    </div>
                    </form>
            </div>
        </div>
    </div>
{% endblock content%}

Tra_dirigido/templates/usuarios/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Cambiar Contraseña
{% endblock title %}

{% block content%}
    <div class="grid-container" style="height: 100vh;">
        <div class="grid-x align-center-middle" style="height: 100%;">
            <div class="cell large-8 text-center">
                <h1>Cambiar Contraseña: {{user.username}}</h1>
            </div>
            <div class="cell large-4 text-center">
                <form method="POST">{% csrf_token %}
                    <div>
                        {{ form.as_p }}
                        <button type="submit" class="button expanded">Actualizar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content%}