Tra_dirigido/Tra_dirigido/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.historial_precio.urls')),
    path('', include('applications.productos.urls')),
    path('', include('applications.productos_seleccionados.urls')),
    #path('', include('applications.usuarios.urls')),
    re_path('', include('applications.users.urls')),
]

Tra_dirigido/applications/historial_precio/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "historial_app"

urlpatterns = [
    path('history/',
         views.ListaHistorialPrecio.as_view(),
        name="historial"),
    path('historial/<id>',
         views.ListaHistorial.as_view(),
        name="historia"),
]

Tra_dirigido/applications/productos_seleccionados/urls.py
from django.urls import path
from . import views

app_name = "productosSeleccionado_app"

urlpatterns = [
    path('productsSelect/<pk>',
         views.IndexView.as_view(),
         name='producto-seleccionados'),
    path('Favoritos/',
         views.ConsultarFavoritos.as_view(),
         name='favoritos'),
    path('deleteFavorite/<pk>',
         views.EliminarFavorito.as_view(),
         name='delete-favorito'),
]

Tra_dirigido/applications/productos_seleccionados/models.py
from django.db import models
from applications.users.models import User
from applications.productos.models import Productos

from .managers import ProductosSelecionaadosManager
# Create your models here.
class Productos_Seleccionados(models.Model):
    userId = models.ForeignKey(User, on_delete=models.CASCADE, )
    productId = models.ForeignKey(Productos, on_delete=models.CASCADE, related_name='products_user')

    class Meta:
        verbose_name = 'Productos Seleccionados'
        unique_together = ('userId', 'productId')

    objects = ProductosSelecionaadosManager()
    def __str__(self):
        return (str(self.userId) + '-' +
                str(self.productId))

Tra_dirigido/applications/productos_seleccionados/forms.py
from django import forms

from .models import Productos_Seleccionados

Tra_dirigido/applications/productos_seleccionados/views.py
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DeleteView
from .models import Productos_Seleccionados, Productos
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
# Create your views here.


class IndexView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users_app:user-login')
    def post(self, request, *args, **kwargs):
        usuario = get_user_model().objects.get(pk=request.user.id)
        producto, created = Productos.objects.get_or_create(productId=self.kwargs['pk'])

        productos_seleccionados_exists = Productos_Seleccionados.objects.filter(
            userId=usuario,
            productId=producto,
        ).exists()

        if not productos_seleccionados_exists:
            Productos_Seleccionados.objects.create(
                userId=usuario,
                productId=producto,
            )
        return HttpResponseRedirect(
            reverse('productosSeleccionado_app:favoritos')
        )
class ConsultarFavoritos(LoginRequiredMixin, ListView):

    template_name = 'productos_seleccionados/productos_seleccionados.html'
    paginate_by = 4
    context_object_name = 'Favoritos'
    login_url = reverse_lazy('users_app:user-login')
    def get_queryset(self):
        return Productos_Seleccionados.objects.ConsultarFavoritos(self.request.user)
class EliminarFavorito(LoginRequiredMixin, DeleteView):
    model = Productos_Seleccionados
    success_url = reverse_lazy('productosSeleccionado_app:favoritos')

Tra_dirigido/templates/productos_seleccionados/productos_seleccionados.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Productos Seleccionado
{% endblock title %}


<{% block content%}
    {% include 'includes/header.html'%}
    <div class="grid-container">
        <div class="grid-x">
                <h1 class="cell">Productos Seleccionados</h1>
        </div>
        <div class="cell">
                <table>
                      <thead>
                        <tr>
                            <th style="width:100px;">ID Producto</th>
                            <th style="width:50px;">Almacen</th>
                            <th style="width:150px;">Nombre</th>
                            <th style="width:50px;">Categoria</th>
                            <th style="width:50px;">Marca</th>
                            <th style="width:150px">Descripción</th>
                            <th style="width:150px;">Historial<th>
                            <th style="width:150px;"><th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for favorito in Favoritos %}
                        <tr>
                            <td>{{favorito.productId.productId}}</td>
                            <td>{{favorito.productId.store}}</td>
                            <td>{{favorito.productId.name}}</td>
                            <td>{{favorito.productId.category}}</td>
                            <td>{{favorito.productId.make}}</td>
                            <td>{{favorito.productId.describe}}</td>
                            <td><a class="button warning" href="{% url 'historial_app:historia' favorito.productId.productId %}">Ver Historial</a></td>
                            <td>
                                <form method="POST" action="{% url 'productosSeleccionado_app:delete-favorito' favorito.id %}">{% csrf_token %}
                                    <button type="submit" class="button alert">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                </table>
                <div class="cell">

                    {% if  is_paginated%}
                        <nav aria-label="Pagination">
                          <ul class="pagination text-center">

                              {% if page_obj.has_previous%}
                                <li class="pagination-previous">
                                    <a href="?page={{page_obj.previous_page_number}}&kword={{ request.GET.kword }}&csrfmiddlewaretoken={{ csrf_token }}">atras</a>
                                </li>
                              {% endif %}

                              {% for pagina in paginator.page_range %}

                                  {% if pagina == page_obj.number %}
                                        <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                                  {% else %}
                                        <li><a href="?page={{pagina}}&kword={{ request.GET.kword }}&csrfmiddlewaretoken={{ csrf_token }}">{{pagina}}</a></li>
                                  {% endif %}

                              {% endfor %}

                              {% if page_obj.has_next%}
                                <li class="pagination-next">
                                    <a href="?page={{page_obj.next_page_number}}&kword={{ request.GET.kword }}&csrfmiddlewaretoken={{ csrf_token }}">Siguiente</a>
                                </li>
                              {% endif %}

                          </ul>
                        </nav>
                    {% endif %}
                </div>
        </div>
    </div>


{% endblock content%}