Tra_dirigido/Tra_dirigido/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.historial_precio.urls')),
    path('', include('applications.productos.urls')),
    path('', include('applications.productos_seleccionados.urls')),
    #path('', include('applications.usuarios.urls')),
    re_path('', include('applications.users.urls')),
]

Tra_dirigido/applications/historial_precio/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "historial_app"

urlpatterns = [
    path('history/',
         views.ListaHistorialPrecio.as_view(),
        name="historial"),
    path('historial/<id>',
         views.ListaHistorial.as_view(),
        name="historia"),
]

Tra_dirigido/applications/productos/urls.py
from django.urls import path
from . import views


app_name = "productos_app"
urlpatterns = [
    path('ProductsPrice/',
         views.getProductoByPrice.as_view(),
         name="producto"
         ),
    path('ProductsSave/',
         views.SaveProducts.as_view(),
         name="producto-save"
         ),
    path('DelData/',
         views.BorrarDatos.as_view(),
         name="Delete"),
]

Tra_dirigido/applications/productos_seleccionados/urls.py
from django.urls import path
from . import views

app_name = "productosSeleccionado_app"

urlpatterns = [
    path('productsSelect/<pk>',
         views.IndexView.as_view(),
         name='producto-seleccionados'),
    path('Favoritos/',
         views.ConsultarFavoritos.as_view(),
         name='favoritos'),
    path('deleteFavorite/<pk>',
         views.EliminarFavorito.as_view(),
         name='delete-favorito'),
]

Tra_dirigido/applications/productos/models.py
from django.db import models

# Create your models here.



class Productos(models.Model):
    productId = models.IntegerField('Id', primary_key=True,auto_created=False )
    store = models.CharField('Almacen', max_length=20)
    name = models.CharField('Nombre', max_length=100)
    category = models.CharField('Categoria', max_length=100)
    make = models.CharField('marca', max_length=50)
    describe = models.CharField('Descripción', max_length=100, null=True)
    basicNeed = models.BooleanField('Nececidad Basica', max_length=1, null=True)

    class Meta:
        verbose_name = 'Productos'
        verbose_name_plural = "Productos"
        unique_together = ('productId', 'store')

    def __str__(self):
        return (str(self.productId) + '-' +
                str(self.store) + '-' +
                str(self.name) + '-' +
                str(self.category) + '-' +
                str(self.make) + '-' +
                str(self.describe) + '-' +
                str(self.basicNeed))

Tra_dirigido/applications/productos/views.py
import decimal

from django.shortcuts import render
from django.views.generic import ListView
from django.views import View
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Q


from .models import Productos
from applications.historial_precio.models import Historial_precio

from .ScrapyPages.DUno import cargarProductosD1
from .ScrapyPages.productosExito import cargarProductosExito
from .ScrapyPages.jumbo import cargarProductosJumbo



class getProductoByPrice(LoginRequiredMixin, ListView):
    template_name = "productos/getProducto.html"
    paginate_by = 20
    context_object_name = 'Productos'
    login_url = reverse_lazy('users_app:user-login')

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        if palabra_clave:
            lista_productos = Productos.objects.filter(
                Q(name__icontains=palabra_clave) | Q(name__iexact=palabra_clave)
            )
            resultados = []
            for producto in lista_productos:
                precio = Historial_precio.objects.filter(
                    productId=producto
                ).order_by('-date').values('price').exclude(price=None).exclude(price=0).first()
                if precio:
                    resultados.append((producto, precio['price']))
            resultados.sort(key=lambda x: x[1] if x[1] is not None else decimal.Decimal(0))

        else:
            resultados = []

        #print('lista resultados: ', lista_productos)
        #print('precios: ', precio)
        #print('resultados', resultados)
        return resultados
class SaveProducts(LoginRequiredMixin, View):
    template_inicio = "productos/getProductsByPrice.html"
    template_respuesta = "productos/ChargueResult.html"
    login_url = reverse_lazy('users_app:user-login')
    def get(self, requests):
        producto_a_buscar = requests.GET.get('kword')

        if not producto_a_buscar:
            return render(requests, self.template_inicio)
        else:
            productos_a_buscar = producto_a_buscar.split(",")

            cargarProductosExito(productos_a_buscar)

            cargarProductosD1()

            cargarProductosJumbo()

            resultado_busqueda = (f"Se guardaron exitosamente los productos de  '{producto_a_buscar} de exito"
                                  f" y todos los de D1 y jumbo'")

            return render(requests, self.template_respuesta, {'resultadoCargue': resultado_busqueda})

class BorrarDatos(LoginRequiredMixin, View):
    template_respuesta = "productos/ChargueResult.html"
    login_url = reverse_lazy('users_app:user-login')
    def get(self, requests):
        requests.GET

        Productos.objects.all().delete()
        Historial_precio.objects.all().delete()

        resultado_busqueda = f"Se borraron de manera exitosa los datos de las tablas Productos e Historial"

        return render(requests, self.template_respuesta, {'resultadoCargue': resultado_busqueda})

Tra_dirigido/templates/productos/ChargueResult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resultado Cargue Productos</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        h1 {
            text-align: center;
            color: #333;
            background-color: #3498DB;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <h1>{{ resultadoCargue }}</h1>
</body>
</html>

Tra_dirigido/templates/productos/getProducto.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Buscar Productos
{% endblock title %}
{% block content%}
    {% include 'includes/header.html'%}
        <div class="grid-container">
            <div class="grid-x">
                <h1 class="cell">Buscar Productos</h1>
                <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                    <div class = "cell large-6">
                        <input type="text" id="kword" name="kword"  placeholder="Ingrese producto aqui">
                    </div>
                    <div class= "cell large-2">
                        <button class="submit success button">Buscar</button>
                    </div>
                </form>
                <div class="cell">
                    <table>
                      <thead>
                        <tr>
                            <th style="width:100px;">ID</th>
                            <th style="width:50px;">Almacen</th>
                            <th style="width:100px;">Nombre</th>
                            <th style="width:150px;">Categoria</th>
                            <th style="width:50px;">Marca</th>
                            <th style="width:150px";>Descripción</th>
                            <th style="width:20px;">Primera Nececidad</th>
                            <th style="width:50px;">Precio</th>
                            <th style="width:50px;">Historial<th>
                            <th style="width:150px;"><th>


                        </tr>
                      </thead>
                      <tbody>
                        {% for producto_item, precio in Productos %}
                        <tr>
                            <td>{{producto_item.productId}}</td>
                            <td>{{producto_item.store}}</td>
                            <td>{{producto_item.name}}</td>
                            <td>{{producto_item.category}}</td>
                            <td>{{producto_item.make}}</td>
                            <td>{{producto_item.describe}}</td>
                            <td>{{producto_item.basicNeed}}</td>
                            <td>{{precio}}</td>
                            <td>
                                <a class="button warning" href="{% url 'historial_app:historia' producto_item.productId %}">Ver Historial</a>
                            </td>
                            <td>
                                <form method="POST" action="{% url 'productosSeleccionado_app:producto-seleccionados' producto_item.productId %}">{% csrf_token %}
                                    <button type="submit" class="button success">Favorito</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                </div>
                <div class="cell">

                    {% if  is_paginated%}
                        <nav aria-label="Pagination">
                          <ul class="pagination text-center">

                              {% if page_obj.has_previous%}
                                <li class="pagination-previous">
                                    <a href="?page={{page_obj.previous_page_number}}&kword={{ request.GET.kword }}&csrfmiddlewaretoken={{ csrf_token }}">atras</a>
                                </li>
                              {% endif %}

                              {% for pagina in paginator.page_range %}

                                  {% if pagina == page_obj.number %}
                                        <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                                  {% else %}
                                        <li><a href="?page={{pagina}}&kword={{ request.GET.kword }}&csrfmiddlewaretoken={{ csrf_token }}">{{pagina}}</a></li>
                                  {% endif %}

                              {% endfor %}

                              {% if page_obj.has_next%}
                                <li class="pagination-next">
                                    <a href="?page={{page_obj.next_page_number}}&kword={{ request.GET.kword }}&csrfmiddlewaretoken={{ csrf_token }}">atras</a>
                                </li>
                              {% endif %}

                          </ul>
                        </nav>
                    {% endif %}
                </div>
            </div>
        </div>
{% endblock content%}

Tra_dirigido/templates/productos/getProductsByPrice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Búsqueda de Producto</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;

            margin: 10vh;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f0f0f0;
            border: 2px solid #000;
            border-radius: 10px;
        }

        #contenido {
            width: 400px;
            text-align: center;
        }

        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
            display: block;
        }

        form {
            text-align: center;
        }

        label {
            display: block;
            margin-bottom: 10px;
            color: #555;
        }

        input {
            padding: 8px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            margin-bottom: 10px;
            width: 400px;
        }

        button {
            padding: 10px 20px;
            font-size: 16px;
            background-color: #3498DB;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #2471A3;
        }
    </style>
</head>
<body>
    <div id="contenido">
        <h1>Cargar Productos</h1>
        <form method="get">
            <label for="kword">Ingrese el nombre del producto:</label>
            <input type="text" id="kword" name="kword" placeholder="Escriba los nombres de producto separados por ','">
            <button type="submit">Buscar</button>
        </form>
    </div>
</body>
</html>